test_communication_and_logic (test_integration.TestIntegration) ... [0m[INFO] [1754405556.733492474] [test_subscriber_node]: 测试节点test_subscriber_node已创建[0m
[0m[INFO] [1754405559.803357935] [test_subscriber_node]: 检查接收到的消息。 Got: [3, 6, 9][0m
[0m[INFO] [1754405559.808182019] [test_subscriber_node]: 测试结束，销毁测试节点[0m
FAIL
test_processor_starts_ok (test_integration.TestIntegration) ... [0m[INFO] [1754405559.817745889] [test_subscriber_node]: 测试节点test_subscriber_node已创建[0m
[0m[INFO] [1754405559.818225566] [test_subscriber_node]: 正在检查 processor 节点的启动日志...[0m
[0m[INFO] [1754405559.818733739] [test_subscriber_node]: Processor 节点启动正常。[0m
[0m[INFO] [1754405559.822637650] [test_subscriber_node]: 测试结束，销毁测试节点[0m
ok
test_publisher_starts_ok (test_integration.TestIntegration) ... [0m[INFO] [1754405559.830134394] [test_subscriber_node]: 测试节点test_subscriber_node已创建[0m
[0m[INFO] [1754405559.830604573] [test_subscriber_node]: 正在检查 publisher 节点的启动日志...[0m
[0m[INFO] [1754405559.831086625] [test_subscriber_node]: Publisher 节点启动正常。[0m
[0m[INFO] [1754405559.835091458] [test_subscriber_node]: 测试结束，销毁测试节点[0m
ok

======================================================================
FAIL: test_communication_and_logic (test_integration.TestIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/phr/vscode_project/ros2_launch_testing_ws/src/my_testing/test/test_integration.py", line 84, in test_communication_and_logic
    self.assertEqual(sorted(self.received_messages), sorted(expected_results))
AssertionError: Lists differ: [3, 6, 9] != [2, 4, 6]

First differing element 0:
3
2

- [3, 6, 9]
+ [2, 4, 6]

----------------------------------------------------------------------
Ran 3 tests in 3.136s

FAILED (failures=1)

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
