[1m============================= test session starts ==============================[0m
platform linux -- Python 3.10.12, pytest-6.2.5, py-1.10.0, pluggy-0.13.0
cachedir: /home/phr/vscode_project/ros2_launch_testing_ws/build/my_testing/.pytest_cache
rootdir: /home/phr/vscode_project/ros2_launch_testing_ws/src/my_testing
plugins: launch-testing-1.0.10, ament-lint-0.12.14, ament-copyright-0.12.14, ament-xmllint-0.12.14, launch-testing-ros-0.19.10, ament-pep257-0.12.14, ament-flake8-0.12.14, colcon-core-0.19.0, cov-3.0.0
[1mcollecting ... [0m[1m
collected 1 item                                                               [0m

test/test_integration.py [INFO] [launch]: All log files can be found below /home/phr/.ros/log/2025-08-05-22-43-27-416244-PHR-54230
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [number_publisher-1]: process started with pid [54244]
[INFO] [number_processor-2]: process started with pid [54246]
test_communication_and_logic (test_integration.TestIntegration) ... [0m[INFO] [1754405007.458808819] [test_subscriber_node]: 测试节点test_subscriber_node已创建[0m
[number_publisher-1] [INFO] [1754405007.532132819] [number_publisher]: 数字发布节点已启动，将从1开始发布...
[number_processor-2] [INFO] [1754405007.532475954] [number_processor]: 数字处理节点已启动，等待接收数字...
[number_publisher-1] [INFO] [1754405008.527321267] [number_publisher]: 发布: 1
[number_processor-2] [INFO] [1754405008.527631157] [number_processor]: 收到: 1
[number_processor-2] [INFO] [1754405008.528304366] [number_processor]: 发布处理后结果: 3
[number_publisher-1] [INFO] [1754405009.527304111] [number_publisher]: 发布: 2
[number_processor-2] [INFO] [1754405009.527579569] [number_processor]: 收到: 2
[number_processor-2] [INFO] [1754405009.528149481] [number_processor]: 发布处理后结果: 6
[number_publisher-1] [INFO] [1754405010.527031689] [number_publisher]: 发布: 3
[number_processor-2] [INFO] [1754405010.527184853] [number_processor]: 收到: 3
[number_processor-2] [INFO] [1754405010.527482870] [number_processor]: 发布处理后结果: 9
[0m[INFO] [1754405010.528378108] [test_subscriber_node]: 检查接收到的消息。 Got: [3, 6, 9][0m
[0m[INFO] [1754405010.531279912] [test_subscriber_node]: 测试结束，销毁测试节点[0m
FAIL
test_processor_starts_ok (test_integration.TestIntegration) ... [0m[INFO] [1754405010.537540640] [test_subscriber_node]: 测试节点test_subscriber_node已创建[0m
[0m[INFO] [1754405010.537789976] [test_subscriber_node]: 正在检查 processor 节点的启动日志...[0m
[number_publisher-1] [INFO] [1754405011.527038294] [number_publisher]: 发布: 4
[number_processor-2] [INFO] [1754405011.527138029] [number_processor]: 收到: 4
[number_processor-2] [INFO] [1754405011.527363620] [number_processor]: 发布处理后结果: 12
[number_publisher-1] [INFO] [1754405012.527320365] [number_publisher]: 发布: 5
[number_processor-2] [INFO] [1754405012.527656376] [number_processor]: 收到: 5
[number_processor-2] [INFO] [1754405012.528208479] [number_processor]: 发布处理后结果: 15
[number_publisher-1] [INFO] [1754405013.527023032] [number_publisher]: 发布: 6
[number_processor-2] [INFO] [1754405013.527309175] [number_processor]: 收到: 6
[number_processor-2] [INFO] [1754405013.527651123] [number_processor]: 发布处理后结果: 18
[0m[INFO] [1754405013.540172577] [test_subscriber_node]: 测试结束，销毁测试节点[0m
FAIL
test_publisher_starts_ok (test_integration.TestIntegration) ... [0m[INFO] [1754405013.544470668] [test_subscriber_node]: 测试节点test_subscriber_node已创建[0m
[0m[INFO] [1754405013.544693884] [test_subscriber_node]: 正在检查 publisher 节点的启动日志...[0m
[number_publisher-1] [INFO] [1754405014.527296806] [number_publisher]: 发布: 7
[number_processor-2] [INFO] [1754405014.527618569] [number_processor]: 收到: 7
[number_processor-2] [INFO] [1754405014.528176608] [number_processor]: 发布处理后结果: 21
[number_publisher-1] [INFO] [1754405015.527305815] [number_publisher]: 发布: 8
[number_processor-2] [INFO] [1754405015.527610956] [number_processor]: 收到: 8
[number_processor-2] [INFO] [1754405015.528375589] [number_processor]: 发布处理后结果: 24
[number_publisher-1] [INFO] [1754405016.527330267] [number_publisher]: 发布: 9
[number_processor-2] [INFO] [1754405016.527605725] [number_processor]: 收到: 9
[number_processor-2] [INFO] [1754405016.528257562] [number_processor]: 发布处理后结果: 27
[0m[INFO] [1754405016.548793413] [test_subscriber_node]: 测试结束，销毁测试节点[0m
FAIL

======================================================================
FAIL: test_communication_and_logic (test_integration.TestIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/phr/vscode_project/ros2_launch_testing_ws/src/my_testing/test/test_integration.py", line 84, in test_communication_and_logic
    self.assertEqual(sorted(self.received_messages), sorted(expected_results))
AssertionError: Lists differ: [3, 6, 9] != [2, 4, 6]

First differing element 0:
3
2

- [3, 6, 9]
+ [2, 4, 6]

======================================================================
FAIL: test_processor_starts_ok (test_integration.TestIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/phr/vscode_project/ros2_launch_testing_ws/src/my_testing/test/test_integration.py", line 65, in test_processor_starts_ok
    proc_output.assertWaitFor('数字处理节点已启动，等待接收数字...',process='number_processor',stream='stdout',timeout=3)
  File "/opt/ros/humble/lib/python3.10/site-packages/launch_testing/io_handler.py", line 146, in assertWaitFor
    assert success, 'Waiting for output timed out'
AssertionError: Waiting for output timed out

======================================================================
FAIL: test_publisher_starts_ok (test_integration.TestIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/phr/vscode_project/ros2_launch_testing_ws/src/my_testing/test/test_integration.py", line 59, in test_publisher_starts_ok
    proc_output.assertWaitFor('数字发布节点已启动，将从1开始发布...',process='number_publisher',stream='stdout',timeout=3)
  File "/opt/ros/humble/lib/python3.10/site-packages/launch_testing/io_handler.py", line 146, in assertWaitFor
    assert success, 'Waiting for output timed out'
AssertionError: Waiting for output timed out

----------------------------------------------------------------------
Ran 3 tests in 9.124s

FAILED (failures=3)
[INFO] [number_processor-2]: sending signal 'SIGINT' to process[number_processor-2]
[INFO] [number_publisher-1]: sending signal 'SIGINT' to process[number_publisher-1]
[number_processor-2] Traceback (most recent call last):
[number_processor-2]   File "/home/phr/vscode_project/ros2_launch_testing_ws/install/my_algorithms/lib/my_algorithms/number_processor", line 33, in <module>
[number_processor-2]     sys.exit(load_entry_point('my-algorithms==0.0.0', 'console_scripts', 'number_processor')())
[number_processor-2]   File "/home/phr/vscode_project/ros2_launch_testing_ws/install/my_algorithms/lib/python3.10/site-packages/my_algorithms/number_processor_node.py", line 32, in main
[number_processor-2]     rclpy.spin(node)
[number_processor-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 229, in spin
[number_processor-2]     executor.spin_once()
[number_processor-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 751, in spin_once
[number_publisher-1] Traceback (most recent call last):
[number_publisher-1]   File "/home/phr/vscode_project/ros2_launch_testing_ws/install/my_algorithms/lib/my_algorithms/number_publisher", line 33, in <module>
[number_publisher-1]     sys.exit(load_entry_point('my-algorithms==0.0.0', 'console_scripts', 'number_publisher')())
[number_publisher-1]   File "/home/phr/vscode_project/ros2_launch_testing_ws/install/my_algorithms/lib/python3.10/site-packages/my_algorithms/number_publisher_node.py", line 25, in main
[number_publisher-1]     rclpy.spin(node)
[number_publisher-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 229, in spin
[number_publisher-1]     executor.spin_once()
[number_publisher-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 751, in spin_once
[number_processor-2]     self._spin_once_impl(timeout_sec)
[number_processor-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 740, in _spin_once_impl
[number_processor-2]     handler, entity, node = self.wait_for_ready_callbacks(timeout_sec=timeout_sec)
[number_processor-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 723, in wait_for_ready_callbacks
[number_processor-2]     return next(self._cb_iter)
[number_processor-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 620, in _wait_for_ready_callbacks
[number_processor-2]     wait_set.wait(timeout_nsec)
[number_processor-2] KeyboardInterrupt
[number_publisher-1]     self._spin_once_impl(timeout_sec)
[number_publisher-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 740, in _spin_once_impl
[number_publisher-1]     handler, entity, node = self.wait_for_ready_callbacks(timeout_sec=timeout_sec)
[number_publisher-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 723, in wait_for_ready_callbacks
[number_publisher-1]     return next(self._cb_iter)
[number_publisher-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 620, in _wait_for_ready_callbacks
[number_publisher-1]     wait_set.wait(timeout_nsec)
[number_publisher-1] KeyboardInterrupt
[ERROR] [number_publisher-1]: process has died [pid 54244, exit code -2, cmd '/home/phr/vscode_project/ros2_launch_testing_ws/install/my_algorithms/lib/my_algorithms/number_publisher --ros-args -r __node:=number_publisher'].
[ERROR] [number_processor-2]: process has died [pid 54246, exit code -2, cmd '/home/phr/vscode_project/ros2_launch_testing_ws/install/my_algorithms/lib/my_algorithms/number_processor --ros-args -r __node:=number_processor'].

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
[31mF[0m

=================================== FAILURES ===================================
[31m[1m________________________ launch tests: test_integration ________________________[0m

==========================================================================================================================================
FAIL: test_integration.TestIntegration.test_communication_and_logic
------------------------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/phr/vscode_project/ros2_launch_testing_ws/src/my_testing/test/test_integration.py", line 84, in test_communication_and_logic
    self.assertEqual(sorted(self.received_messages), sorted(expected_results))
AssertionError: Lists differ: [3, 6, 9] != [2, 4, 6]

First differing element 0:
3
2

- [3, 6, 9]
+ [2, 4, 6]


==========================================================================================================================================
FAIL: test_integration.TestIntegration.test_processor_starts_ok
------------------------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/phr/vscode_project/ros2_launch_testing_ws/src/my_testing/test/test_integration.py", line 65, in test_processor_starts_ok
    proc_output.assertWaitFor('数字处理节点已启动，等待接收数字...',process='number_processor',stream='stdout',timeout=3)
  File "/opt/ros/humble/lib/python3.10/site-packages/launch_testing/io_handler.py", line 146, in assertWaitFor
    assert success, 'Waiting for output timed out'
AssertionError: Waiting for output timed out


==========================================================================================================================================
FAIL: test_integration.TestIntegration.test_publisher_starts_ok
------------------------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/phr/vscode_project/ros2_launch_testing_ws/src/my_testing/test/test_integration.py", line 59, in test_publisher_starts_ok
    proc_output.assertWaitFor('数字发布节点已启动，将从1开始发布...',process='number_publisher',stream='stdout',timeout=3)
  File "/opt/ros/humble/lib/python3.10/site-packages/launch_testing/io_handler.py", line 146, in assertWaitFor
    assert success, 'Waiting for output timed out'
AssertionError: Waiting for output timed out
- generated xml file: /home/phr/vscode_project/ros2_launch_testing_ws/build/my_testing/pytest.xml -
=========================== short test summary info ============================
FAILED test/test_integration.py::test_integration - test_integration.TestInte...
[31m============================== [31m[1m1 failed[0m[31m in 9.24s[0m[31m ===============================[0m
